CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `csbcdb`.`vt_csbc_code` AS select cast(`c`.`id` as char(10) charset utf8) AS `id`,`c`.`code_name` AS `code_name`,`p`.`path_name` AS `adr_path`,`t`.`code_type_name` AS `code_type`,`u`.`user_code` AS `rec_user`,date_format(`c`.`rec_date`,'%d.%m.%Y %H:%i') AS `rec_date`,`c`.`rec_date` AS `rec_time`,`c`.`id` AS `code_id` from (((`csbcdb`.`csbc_code` `c` join `csbcdb`.`csbc_path` `p`) join `csbcdb`.`csbc_code_type` `t`) join `csbcdb`.`csbc_user` `u`) where ((`c`.`adr_path` = `p`.`id`) and (`c`.`code_type` = `t`.`id`) and (`c`.`rec_user` = `u`.`id`)) order by `c`.`id`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `csbcdb`.`vt_csbc_code_map` AS select cast(`c`.`id` as char(10) charset utf8) AS `id`,`c`.`code_name` AS `mapped_code`,`pl`.`link_name` AS `page_link`,`u`.`user_code` AS `rec_user`,date_format(`cm`.`rec_date`,'%d.%m.%Y %H:%i') AS `rec_date`,`cm`.`rec_date` AS `rec_date1`,`cm`.`rec_date` AS `rec_date2`,`cm`.`id` AS `code_map_id` from ((((`csbcdb`.`csbc_code_map` `cm` join `csbcdb`.`csbc_code` `c`) join `csbcdb`.`csbc_page_link` `pl`) join `csbcdb`.`csbc_user` `u`) join `csbcdb`.`csbc_path` `pt`) where ((`cm`.`mapped_code` = `c`.`id`) and (`cm`.`page_link` = `pl`.`id`) and (`cm`.`rec_user` = `u`.`id`) and (`pl`.`adr_path` = `pt`.`id`)) order by `cm`.`id`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `csbcdb`.`vt_csbc_code_type` AS select cast(`csbcdb`.`csbc_code_type`.`id` as char(10) charset utf8) AS `id`,`csbcdb`.`csbc_code_type`.`code_type_name` AS `code_type_name`,`csbcdb`.`csbc_code_type`.`id` AS `code_type_id` from `csbcdb`.`csbc_code_type` order by `csbcdb`.`csbc_code_type`.`id`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `csbcdb`.`vt_csbc_contact` AS select cast(`c`.`id` as char(10) charset utf8) AS `id`,`c`.`contact_name` AS `contact_name`,`c`.`e_mail` AS `e_mail`,`c`.`web_site` AS `web_site`,`c`.`message_data` AS `message_data`,`u`.`user_code` AS `rec_user`,date_format(`c`.`rec_date`,'%d.%m.%Y %H:%i') AS `rec_date`,`c`.`id` AS `contact_id` from (`csbcdb`.`csbc_contact` `c` left join `csbcdb`.`csbc_user` `u` on((`c`.`rec_user` = `u`.`id`))) order by `c`.`id`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `csbcdb`.`vt_csbc_file` AS select cast(`f`.`id` as char(10) charset utf8) AS `id`,`f`.`file_name` AS `file_name`,`p`.`path_name` AS `adr_path`,`ft`.`file_type_name` AS `file_type`,`f`.`file_size` AS `file_size`,`f`.`mime_type` AS `mime_type`,`u`.`user_code` AS `rec_user`,date_format(`f`.`rec_date`,'%d.%m.%Y %H:%i') AS `rec_date`,`f`.`rec_date` AS `rec_date1`,`f`.`rec_date` AS `rec_date2`,`f`.`id` AS `file_id` from (((`csbcdb`.`csbc_file` `f` join `csbcdb`.`csbc_path` `p`) join `csbcdb`.`csbc_file_type` `ft`) join `csbcdb`.`csbc_user` `u`) where ((`f`.`adr_path` = `p`.`id`) and (`f`.`file_type` = `ft`.`id`) and (`f`.`rec_user` = `u`.`id`)) order by `f`.`id`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `csbcdb`.`vt_csbc_file_type` AS select cast(`csbcdb`.`csbc_file_type`.`id` as char(10) charset utf8) AS `id`,`csbcdb`.`csbc_file_type`.`file_type_name` AS `file_type_name`,`csbcdb`.`csbc_file_type`.`id` AS `file_type_id` from `csbcdb`.`csbc_file_type` order by `csbcdb`.`csbc_file_type`.`id`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `csbcdb`.`vt_csbc_group` AS select cast(`g`.`id` as char(10) charset utf8) AS `id`,`g`.`group_name` AS `group_name`,`g`.`id` AS `group_id` from `csbcdb`.`csbc_group` `g`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `csbcdb`.`vt_csbc_group_s` AS select cast(`g`.`id` as char(10) charset utf8) AS `id`,`g`.`group_name` AS `group_name`,`g`.`id` AS `group_id` from `csbcdb`.`csbc_group` `g` where (`g`.`group_name` <> 'Admin');

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `csbcdb`.`vt_csbc_image` AS select cast(`m`.`id` as char(10) charset utf8) AS `id`,`m`.`image_name` AS `image_name`,`p`.`path_name` AS `adr_path`,`u`.`user_code` AS `rec_user`,date_format(`m`.`rec_date`,'%d.%m.%Y %H:%i') AS `rec_date`,`m`.`rec_date` AS `rec_date1`,`m`.`rec_date` AS `rec_date2`,`m`.`id` AS `image_id` from ((`csbcdb`.`csbc_image` `m` join `csbcdb`.`csbc_path` `p`) join `csbcdb`.`csbc_user` `u`) where ((`m`.`adr_path` = `p`.`id`) and (`m`.`rec_user` = `u`.`id`));

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `csbcdb`.`vt_csbc_log` AS select cast(`l`.`id` as char(10) charset utf8) AS `id`,`l`.`rec_id` AS `rec_id`,`f`.`log_form_name` AS `form_name`,`t`.`log_type_name` AS `type_name`,`b`.`log_table_name` AS `table_name`,`l`.`log_data` AS `log_data`,`u`.`user_code` AS `rec_user`,date_format(`l`.`rec_date`,'%d.%m.%Y %H:%i') AS `rec_date`,`l`.`rec_date` AS `rec_time`,`l`.`id` AS `log_id` from ((((`csbcdb`.`csbc_log` `l` join `csbcdb`.`csbc_log_table` `b`) join `csbcdb`.`csbc_log_type` `t`) join `csbcdb`.`csbc_log_form` `f`) join `csbcdb`.`csbc_user` `u`) where ((`l`.`form_name` = `f`.`id`) and (`l`.`type_name` = `t`.`id`) and (`l`.`table_name` = `b`.`id`) and (`l`.`rec_user` = `u`.`id`)) order by `l`.`id`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `csbcdb`.`vt_csbc_log_form` AS select cast(`csbcdb`.`csbc_log_form`.`id` as char(10) charset utf8) AS `id`,`csbcdb`.`csbc_log_form`.`log_form_name` AS `log_form_name`,`csbcdb`.`csbc_log_form`.`id` AS `log_form_id` from `csbcdb`.`csbc_log_form` order by `csbcdb`.`csbc_log_form`.`id`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `csbcdb`.`vt_csbc_log_table` AS select cast(`csbcdb`.`csbc_log_table`.`id` as char(10) charset utf8) AS `id`,`csbcdb`.`csbc_log_table`.`log_table_name` AS `log_table_name`,`csbcdb`.`csbc_log_table`.`id` AS `log_table_id` from `csbcdb`.`csbc_log_table` order by `csbcdb`.`csbc_log_table`.`id`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `csbcdb`.`vt_csbc_log_type` AS select cast(`csbcdb`.`csbc_log_type`.`id` as char(10) charset utf8) AS `id`,`csbcdb`.`csbc_log_type`.`log_type_name` AS `log_type_name`,`csbcdb`.`csbc_log_type`.`id` AS `log_type_id` from `csbcdb`.`csbc_log_type` order by `csbcdb`.`csbc_log_type`.`id`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `csbcdb`.`vt_csbc_menu` AS select cast(`m`.`id` as char(10) charset utf8) AS `id`,`m`.`menu_name` AS `menu_name`,`p`.`path_name` AS `adr_path`,`m`.`menu_data` AS `menu_data`,`u`.`user_code` AS `rec_user`,date_format(`m`.`rec_date`,'%d.%m.%Y %H:%i') AS `rec_date`,`m`.`rec_date` AS `rec_date1`,`m`.`rec_date` AS `rec_date2`,`m`.`id` AS `menu_id` from ((`csbcdb`.`csbc_menu` `m` join `csbcdb`.`csbc_path` `p`) join `csbcdb`.`csbc_user` `u`) where ((`m`.`adr_path` = `p`.`id`) and (`m`.`rec_user` = `u`.`id`));

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `csbcdb`.`vt_csbc_message` AS select cast(`m`.`id` as char(10) charset utf8) AS `id`,`m`.`msg_name` AS `msg_name`,`mt`.`msg_type_name` AS `message_type`,`s`.`status_name` AS `rec_status`,`m`.`msg_data` AS `msg_data`,`u`.`user_code` AS `rec_user`,date_format(`m`.`rec_date`,'%d.%m.%Y %H:%i') AS `rec_date`,`m`.`rec_date` AS `rec_date1`,`m`.`rec_date` AS `rec_date2`,`m`.`id` AS `message_id` from (((`csbcdb`.`csbc_message` `m` join `csbcdb`.`csbc_status` `s`) join `csbcdb`.`csbc_user` `u`) join `csbcdb`.`csbc_message_type` `mt`) where ((`m`.`rec_status` = `s`.`id`) and (`m`.`rec_user` = `u`.`id`) and (`m`.`message_type` = `mt`.`id`));

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `csbcdb`.`vt_csbc_message_map` AS select cast(`mm`.`id` as char(10) charset utf8) AS `id`,`m`.`msg_name` AS `mapped_msg`,`g`.`group_name` AS `user_group`,`u`.`user_code` AS `rec_user`,date_format(`mm`.`rec_date`,'%d.%m.%Y %H:%i') AS `rec_date`,`mm`.`rec_date` AS `rec_date1`,`mm`.`rec_date` AS `rec_date2`,`mm`.`id` AS `message_map_id` from (((`csbcdb`.`csbc_message_map` `mm` join `csbcdb`.`csbc_message` `m`) join `csbcdb`.`csbc_group` `g`) join `csbcdb`.`csbc_user` `u`) where ((`mm`.`mapped_msg` = `m`.`id`) and (`mm`.`user_group` = `g`.`id`) and (`mm`.`rec_user` = `u`.`id`));

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `csbcdb`.`vt_csbc_message_type` AS select cast(`csbcdb`.`csbc_message_type`.`id` as char(10) charset utf8) AS `id`,`csbcdb`.`csbc_message_type`.`msg_type_name` AS `msg_type_name`,`csbcdb`.`csbc_message_type`.`id` AS `message_type_id` from `csbcdb`.`csbc_message_type` order by `csbcdb`.`csbc_message_type`.`id`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `csbcdb`.`vt_csbc_page` AS select cast(`p`.`id` as char(10) charset utf8) AS `id`,`p`.`page_name` AS `page_name`,`pt`.`path_name` AS `adr_path`,`py`.`page_type_name` AS `page_type`,`s`.`status_name` AS `rec_status`,`u`.`user_code` AS `rec_user`,date_format(`p`.`rec_date`,'%d.%m.%Y %H:%i') AS `rec_date`,`p`.`rec_date` AS `rec_date1`,`p`.`rec_date` AS `rec_date2`,`p`.`id` AS `page_id` from ((((`csbcdb`.`csbc_page` `p` join `csbcdb`.`csbc_path` `pt`) join `csbcdb`.`csbc_page_type` `py`) join `csbcdb`.`csbc_status` `s`) join `csbcdb`.`csbc_user` `u`) where ((`p`.`adr_path` = `pt`.`id`) and (`p`.`page_type` = `py`.`id`) and (`p`.`rec_status` = `s`.`id`) and (`p`.`rec_user` = `u`.`id`));

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `csbcdb`.`vt_csbc_page_link` AS select cast(`pl`.`id` as char(10) charset utf8) AS `id`,`pl`.`link_name` AS `link_name`,`pt`.`path_name` AS `adr_path`,`p`.`page_name` AS `linked_page`,`ps`.`pos_name` AS `position`,`t`.`theme_name` AS `theme`,`u`.`user_code` AS `rec_user`,date_format(`pl`.`rec_date`,'%d.%m.%Y %H:%i') AS `rec_date`,`pl`.`rec_date` AS `rec_date1`,`pl`.`rec_date` AS `rec_date2`,`pl`.`id` AS `page_link_id` from (((((`csbcdb`.`csbc_page_link` `pl` join `csbcdb`.`csbc_path` `pt`) join `csbcdb`.`csbc_page` `p`) join `csbcdb`.`csbc_position` `ps`) join `csbcdb`.`csbc_theme` `t`) join `csbcdb`.`csbc_user` `u`) where ((`pl`.`adr_path` = `pt`.`id`) and (`pl`.`linked_page` = `p`.`id`) and (`pl`.`position` = `ps`.`id`) and (`pl`.`theme` = `t`.`id`) and (`pl`.`rec_user` = `u`.`id`));

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `csbcdb`.`vt_csbc_page_map` AS select cast(`pm`.`id` as char(10) charset utf8) AS `id`,`p`.`page_name` AS `mapped_page`,`t`.`theme_name` AS `theme`,`ps`.`pos_name` AS `position`,`u`.`user_code` AS `rec_user`,date_format(`pm`.`rec_date`,'%d.%m.%Y %H:%i') AS `rec_date`,`pm`.`rec_date` AS `rec_date1`,`pm`.`rec_date` AS `rec_date2`,`pm`.`id` AS `page_map_id` from ((((`csbcdb`.`csbc_page_map` `pm` join `csbcdb`.`csbc_page` `p`) join `csbcdb`.`csbc_theme` `t`) join `csbcdb`.`csbc_position` `ps`) join `csbcdb`.`csbc_user` `u`) where ((`pm`.`mapped_page` = `p`.`id`) and (`pm`.`theme` = `t`.`id`) and (`pm`.`position` = `ps`.`id`) and (`pm`.`rec_user` = `u`.`id`));

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `csbcdb`.`vt_csbc_page_type` AS select cast(`csbcdb`.`csbc_page_type`.`id` as char(10) charset utf8) AS `id`,`csbcdb`.`csbc_page_type`.`page_type_name` AS `page_type_name`,`csbcdb`.`csbc_page_type`.`id` AS `page_type_id` from `csbcdb`.`csbc_page_type` order by `csbcdb`.`csbc_page_type`.`id`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `csbcdb`.`vt_csbc_path` AS select cast(`csbcdb`.`csbc_path`.`id` as char(10) charset utf8) AS `id`,`csbcdb`.`csbc_path`.`path_name` AS `path_name`,`csbcdb`.`csbc_path`.`id` AS `path_id` from `csbcdb`.`csbc_path` order by `csbcdb`.`csbc_path`.`id`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `csbcdb`.`vt_csbc_position` AS select cast(`csbcdb`.`csbc_position`.`id` as char(10) charset utf8) AS `id`,`csbcdb`.`csbc_position`.`pos_name` AS `pos_name`,`csbcdb`.`csbc_position`.`id` AS `position_id` from `csbcdb`.`csbc_position` order by `csbcdb`.`csbc_position`.`id`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `csbcdb`.`vt_csbc_status` AS select cast(`csbcdb`.`csbc_status`.`id` as char(10) charset utf8) AS `id`,`csbcdb`.`csbc_status`.`status_name` AS `status_name`,`csbcdb`.`csbc_status`.`id` AS `status_id` from `csbcdb`.`csbc_status` order by `csbcdb`.`csbc_status`.`id`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `csbcdb`.`vt_csbc_theme` AS select cast(`t`.`id` as char(10) charset utf8) AS `id`,`t`.`theme_name` AS `theme_name`,`pt`.`path_name` AS `adr_path`,`m`.`menu_name` AS `theme_menu`,`u`.`user_code` AS `rec_user`,date_format(`t`.`rec_date`,'%d.%m.%Y %H:%i') AS `rec_date`,`t`.`rec_date` AS `rec_date1`,`t`.`rec_date` AS `rec_date2`,`t`.`id` AS `theme_id` from (((`csbcdb`.`csbc_theme` `t` join `csbcdb`.`csbc_path` `pt`) join `csbcdb`.`csbc_menu` `m`) join `csbcdb`.`csbc_user` `u`) where ((`t`.`adr_path` = `pt`.`id`) and (`t`.`theme_menu` = `m`.`id`) and (`t`.`rec_user` = `u`.`id`));

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `csbcdb`.`vt_csbc_user` AS select cast(`u`.`id` as char(10) charset utf8) AS `id`,`u`.`user_name` AS `user_name`,`u`.`user_code` AS `user_code`,`u`.`user_psw` AS `user_psw`,`g`.`group_name` AS `user_group`,`u`.`e_mail` AS `e_mail`,`s`.`status_name` AS `rec_status`,`u`.`page_size` AS `page_size`,(select `us`.`user_code` from `csbcdb`.`csbc_user` `us` where (`u`.`rec_user` = `us`.`id`)) AS `rec_user`,date_format(`u`.`rec_date`,'%d.%m.%Y %H:%i') AS `rec_date`,`u`.`rec_date` AS `rec_date1`,`u`.`rec_date` AS `rec_date2`,`u`.`id` AS `user_id` from ((`csbcdb`.`csbc_user` `u` join `csbcdb`.`csbc_group` `g`) join `csbcdb`.`csbc_status` `s`) where ((`u`.`user_group` = `g`.`id`) and (`u`.`rec_status` = `s`.`id`));

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `csbcdb`.`vt_csbc_user_s` AS select cast(`u`.`id` as char(10) charset utf8) AS `id`,`u`.`user_name` AS `user_name`,`u`.`user_code` AS `user_code`,`u`.`user_psw` AS `user_psw`,`g`.`group_name` AS `user_group`,`u`.`e_mail` AS `e_mail`,`s`.`status_name` AS `rec_status`,`u`.`page_size` AS `page_size`,(select `us`.`user_code` from `csbcdb`.`csbc_user` `us` where (`u`.`rec_user` = `us`.`id`)) AS `rec_user`,date_format(`u`.`rec_date`,'%d.%m.%Y %H:%i') AS `rec_date`,`u`.`rec_date` AS `rec_date1`,`u`.`rec_date` AS `rec_date2`,`u`.`id` AS `user_id` from ((`csbcdb`.`csbc_user` `u` join `csbcdb`.`csbc_group` `g`) join `csbcdb`.`csbc_status` `s`) where ((`u`.`user_group` = `g`.`id`) and (`u`.`rec_status` = `s`.`id`) and (`g`.`group_name` <> 'Admin'));

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `csbcdb`.`vt_csbc_view_message` AS select cast(`m`.`id` as char(10) charset utf8) AS `id`,`m`.`msg_name` AS `msg_name`,`mt`.`msg_type_name` AS `message_type`,`s`.`status_name` AS `rec_status`,`m`.`msg_data` AS `msg_data`,`g`.`group_name` AS `user_group`,`u`.`user_code` AS `rec_user`,date_format(`m`.`rec_date`,'%d.%m.%Y %H:%i') AS `rec_date`,`m`.`rec_date` AS `rec_date1`,`m`.`rec_date` AS `rec_date2`,`m`.`id` AS `message_id` from (((((`csbcdb`.`csbc_message` `m` join `csbcdb`.`csbc_status` `s`) join `csbcdb`.`csbc_user` `u`) join `csbcdb`.`csbc_message_type` `mt`) join `csbcdb`.`csbc_message_map` `mm`) join `csbcdb`.`csbc_group` `g`) where ((`m`.`rec_status` = `s`.`id`) and (`m`.`rec_user` = `u`.`id`) and (`m`.`message_type` = `mt`.`id`) and (`m`.`id` = `mm`.`mapped_msg`) and (`mm`.`user_group` = `g`.`id`));
